{"name": "test_s1", "status": "broken", "statusDetails": {"message": "NameError", "trace": "login = None\n\n    def test_s1(login):\n        print(\"用例1：登录之后其它动作111\")\n>       raise NameError\nE       NameError\n\ntest_fixture.py:11: NameError"}, "start": 1618111711579, "stop": 1618111711579, "uuid": "1703021f-d6a6-43bc-9b0e-4bbadb6c1e3c", "historyId": "4841b0381b664b6fd3df8a12ae062dd1", "testCaseId": "544126ce1807384dd653bb3aeb9a450e", "fullName": "test_fixture#test_s1", "labels": [{"name": "suite", "value": "test_fixture"}, {"name": "host", "value": "localhost"}, {"name": "thread", "value": "77635-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_fixture"}]}